name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  filename:
    description: 'A comma separated list of code coverage files to analyse. Also supports using glob patterns to match multiple files.'
    required: true
  badge:
    description: 'Include a coverage badge in the output using shields.io - true / false (default).'
    required: false
    default: 'false'
  overall_fail_threshold:
    description: 'Fail if overall coverage below lower threshold - true / false (default).'
    required: false
    default: '0'
  coverage_color_red_min:
    description: 'Threshold used to determine when coverages less than this value should be marked red'
    required: false
    default: '50'
  coverage_color_orange_max:
    description: 'Threshold used to determine when coverages less than this value should be marked orange'
    required: false
    default: '75'
  fail_on_negative_difference:
    description: 'Fail if any difference is a negative value (Coverage was reduced)'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'