name: 'Code Coverage Report'
description: 'Provides code coverage report in a workflow summary and as a markdown file that can be used in later steps'
author: 'Andrew Nagy'
inputs:
  filename:
    description: 'Code Coverage file to process'
    required: true
  github_token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  markdown_filename:
    description: 'Include a coverage badge in the output using shields.io - true / false (default).'
    required: false
    default: 'code-coverage-results'
  badge:
    description: 'Include a coverage badge in the output using shields.io - true / false (default).'
    required: false
    default: 'false'
  overall_coverage_fail_threshold:
    description: 'Fail if overall coverage below lower threshold - true / false (default).'
    required: false
    default: '0'
  file_coverage_error_min:
    description: 'Threshold used to determine when coverages less than this value should be marked red'
    required: false
    default: '50'
  file_coverage_warning_max:
    description: 'Threshold used to determine when coverages less than this value should be marked orange. Above this will be marked green'
    required: false
    default: '75'
  fail_on_negative_difference:
    description: 'Fail if any difference is a negative value (Coverage was reduced)'
    required: false
    default: 'false'
  artifact_download_workflow_names:
    description: 'Comma Separated list of workflow names to look for artifacts in. If left empty will only look at the current workflow'
    required: false
  artifact_name:
    description: 'Artifact name. Use %name% as a placeholder'
    required: false
    default: 'coverage-%name%'

runs:
  using: 'node16'
  main: 'dist/index.js'