name: "Pull Request"
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - run: npm ci
      - run: npm run lint
      - run: npm run test >> "${GITHUB_STEP_SUMMARY}"
      - run: npm run package
      - uses: ./
        id: code_coverage_report_action
        if: ${{ github.actor != 'dependabot[bot]'}}
        with:
          filename: "coverage/clover.xml"
          artifact_download_workflow_names: "code-coverage-report"
          badge: true
          fail_on_negative_difference: true
          overall_coverage_fail_threshold: 70
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
        with:
          recreate: true
          path: code-coverage-results.md
